version: "3"

networks:
  loki:

services:
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml -log.level=debug
    networks:
      - loki
  promtail:
    image: grafana/promtail:latest
    volumes:
#      - /var/log:/var/log      
      - ./lorem.exe.log:/var/log/lorem.exe.log
      - ./docker-config.yaml:/etc/promtail/docker-config.yaml
    command: -config.file=/etc/promtail/docker-config.yaml -log.level=debug
    networks:
      - loki
