server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
    - targets:
        - localhost
      labels:
        job: varlogs
        __path__: /var/log/*log

  - job_name: problemjob
    pipeline_stages:
      - regex:
          expression: '(?P<timestamp>\d+-\d+-\d+ \d+:\d+:\d+\.\d+) - (?P<level>[a-zA-Z]+) - (?P<logger>[\w\.]+): (?P<message>.+)$'
      - timestamp:
          source:   timestamp
          format:   "2006-01-02 15:04:05.9999"
      - labels:
          level:
          logger:
      - output:
          source: "message"
    static_configs:
      - targets:
          - localhost
        labels:
          __path__: /var/log/lorem.exe.log
